djangoworks/exm/exm/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path("",include("exset1.urls")),
]

djangoworks/exm/exset1/urls.py
from django.urls import path
from exset1 import views

urlpatterns = [
    path("category/",views.CategoryCreateView.as_view(),name='category_add'),
    path("category/<int:pk>/",views.CategoryDetailView.as_view(),name='category-detail'),
    path("product/add",views.ProductCreateView.as_view(),name='product-add'),
    path("product/all",views.ProductListView.as_view(),name='product-list'),
    path("product/<int:pk>/change",views.ProductUpdateView.as_view(),name='product-update'),
     path("product/<int:pk>/remove",views.remove_product,name='product-remove'),
    path("product/<int:pk>/",views.ProductDetailView.as_view(),name='product-detail'),
]

djangoworks/exm/exset1/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    category_name=models.CharField(max_length=200)

    def __str__(self):
        return self.category_name

class Product(models.Model):
    product_name=models.CharField(max_length=200,unique=True)
    category_name=models.ForeignKey(Category,on_delete=models.CASCADE)
    description=models.CharField(max_length=300)
    price=models.PositiveIntegerField(null=True)

    def __str__(self):
        return self.product_name

djangoworks/exm/exset1/forms.py
from django import forms
from exset1.models import Category,Product


class CategoryForm(forms.ModelForm):
    class Meta:
        model=Category
        fields=["category_name"]
    

class ProductForm(forms.ModelForm):
    class Meta:
        model=Product
     
        fields="__all__"

        widgets={

            "product_name":forms.TextInput(attrs={"class":"form-control"}),
             "description":forms.TextInput(attrs={"class":"form-control"}), 
             "price":forms.TextInput(attrs={"class":"form-control"})
        }



class ProductChangeForm(forms.ModelForm):

    class Meta:
        model=Product
        fields="__all__"

        widgets={

            "product_name":forms.TextInput(attrs={"class":"form-control"}),
             "description":forms.TextInput(attrs={"class":"form-control"}), 
             "price":forms.TextInput(attrs={"class":"form-control"})
        }




# class CategorySearchForm(forms.Form):
#     category_name=forms.CharField()
    
    

djangoworks/exm/exset1/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render,redirect
from exset1.forms import CategoryForm,ProductChangeForm,ProductForm
from exset1.models import Category,Product
from django.views.generic import View,CreateView,ListView,UpdateView,DetailView
from django.urls import reverse_lazy

class CategoryCreateView(CreateView,ListView):
    template_name="category_add.html"
    form_class= CategoryForm
    model=Category
    context_object_name="categories"
    success_url=reverse_lazy("category_add")

class CategoryDetailView(DetailView):
    template_name="category_detail.html"
    context_object_name="categories"
    model=Category
   

    


class ProductCreateView(CreateView):
   

    template_name="product_add.html"
    form_class=ProductForm
    model=Product
    success_url=reverse_lazy("product-add")
   

class ProductListView(ListView):
   
    template_name="prod_list.html"
    model=Product
    context_object_name="prod"



class ProductUpdateView(UpdateView):
   
    template_name="prod_update.html"
    success_url=reverse_lazy("product-list")
    form_class=ProductChangeForm
    model=Product

class ProductDetailView(DetailView):
    template_name="productdetail.html"
    model=Product
    context_object_name="p"
    

def remove_product(request,args,*kwargs):
    id=kwargs.get("pk")
    Product.objects.get(id=id).delete()
    return redirect("product-list")
  

djangoworks/exm/exset1/templates/category_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>


<div class="container d-flex flex-column align-items-center mt-5">
    <div class="border border-4 p-5">
     <h1 class="text-center mb-3">Categories</h1>
     <div class="w-100">
      <form action="" method="post">
  
          {%csrf_token%}
          {{form.as_p}}
          <button type="submit" class="btn btn-success form-control">Add</button>
      </form>
  
     </div>
  
     <div class="mt-5 w-100">
      <table class="table table-striped">
          <tr>
              <td>Name</td>
              <td>Action</td>
          </tr>
          {%for cat in categories%}
             <tr>
              <td>{{cat.category_name}}</td>
              <td>
                  <a href="{%url 'category-detail' cat.id%}">view</a>
              </td>
      
             </tr>
          {%endfor%}
      
      </table>
     </div>
  
    </div>
 
 
 </div>

     
</body>
</html>

djangoworks/exm/exset1/templates/category_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>stud</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"> 
    <script src="https://kit.fontawesome.com/c74c679b1d.js" crossorigin="anonymous"></script>


</head>
<body>
<div class="container">
    <div class="row mt-5 ">
        <h2 class="text-center mb-3">Listing all products</h2>
        <div class="col-1"></div>
        <div class="col-10 ">
            <table class="table table-striped table-hover  border border-3 border shadow">
                <tr class="table table-info border border-dark">
                    <td>Name</td>
                    <td>description</td>
                    <td>price</td>
                    <td>Category</td>
                   
                    </tr>
               
                    {%for c in categories.product_set.all%}
                    <tr>
                      <td>{{c.product_name}}</td> 
                      <td>{{c.description}}</td>
                      <td>{{c.price}}</td>
                      <td>{{c.category_name}}</td>
                    

                    </tr>
                    {%endfor%}
               
                    </table>
                   
                    </div>
                    </div>
                    </div>
                    </body>
                    </html>
                    
                

djangoworks/exm/exset1/templates/prod_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>stud</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"> 
    <script src="https://kit.fontawesome.com/c74c679b1d.js" crossorigin="anonymous"></script>


</head>
<body>
<div class="container">
    <div class="row mt-5 ">
        <h2 class="text-center mb-3">Listing all products</h2>
        <div class="col-1"></div>
        <div class="col-10 ">
            <table class="table table-striped table-hover  border border-3 border shadow">
                <tr class="table table-info border border-dark">
                    <td>Name</td>
                    <td>description</td>
                    <td>price</td>
                    <td>Category</td>
                    <td>Action</td>
                    </tr>

                    {%for p in prod%}
                    <tr>
                    <td>{{p.product_name}}</td>
                    <td>{{p.description}}</td>
                    <td>{{p.price}}</td>
                    <td>{{p.category_name}}</td>
                     <td><a href="{% url 'product-update' p.id %}">edit</a>
                        <a href="{% url 'product-remove' p.id %}">delete</a>
                        <a href="{% url 'product-detail' p.id %}">View</a>
                        
                    </td>


                    </tr>
                    {%endfor%}
                    </table>
                   
                    </div>
                    </div>
                    </div>
                    </body>
                    </html>
                    
                

djangoworks/exm/exset1/templates/prod_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student add</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <div class="container mt-5">
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6 shadow p-3">
                <form action="" method="post">
                {%csrf_token%}
                {{form.as_p}}
                <button type="submit" class="btn btn-outline-success form-control">Add</button>
            </form>
            </div>
            <div class="col-3"></div>
        </div>
    </div>
    
</body>
</html>

djangoworks/exm/exset1/templates/product_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student add</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <div class="container mt-5">
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6 shadow p-3">
                <form action="" method="post">
                {%csrf_token%}
                {{form.as_p}}
                <button type="submit" class="btn btn-outline-success form-control">Add</button>
            </form>
            </div>
            <div class="col-3"></div>
        </div>
    </div>
    
</body>
</html>

djangoworks/exm/exset1/templates/productdetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>olx</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"> 
    <script src="https://kit.fontawesome.com/c74c679b1d.js" crossorigin="anonymous"></script>


</head>
<body>
<div class="container">
    <div class="row mt-5 ">
        <h2 class="text-center mb-3">Listing all products</h2>
        <div class="col-1"></div>
        <div class="col-10 ">
            <table class="table table-striped table-hover  border border-3 border shadow">
                <tr class="table table-info border border-dark">
                    <td>Name</td>
                    <td>description</td>
                    <td>price</td>
                    <td>Category</td>
                    <td>Action</td>
                    </tr>

                    <tr>
                    <td>{{p.product_name}}</td>
                    <td>{{p.description}}</td>
                    <td>{{p.price}}</td>
                    <td>{{p.category_name}}</td>


                    </tr>
                   
                    </table>
                   
                    </div>
                    </div>
                    </div>
                    </body>
                    </html>
                    
                